#!/usr/bin/env bash
# This script installs a nginx web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sduo nginx -t
sudo service nginx reload
