#!/bin/bash

# Update the system
sudo apt update
sudo apt upgrade -y

# Install HAproxy
sudo apt install -y haproxy

# Configure HAproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo touch /etc/haproxy/haproxy.cfg

# Add configuration to HAproxy
echo "frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

backend lb-backend
    mode http
    balance roundrobin
    server 209879-web-01 52.201.222.41:80 check
    server 209879-web-02 174.129.54.185:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo systemctl restart haproxy

# Enable HAproxy init script
sudo systemctl enable haproxy

# Verify HAproxy status
sudo systemctl status haproxy

