#!/usr/bin/env bash
# A script to Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
config=\
'
backend selasi-backend
        balance roundrobin
    server 209879-web-01 52.201.222.41:80 check
    server 209879-web-02 174.129.54.185:80 check
frontend selasi-frontend
        bind *:80
        mode http
        default_backend selasi-backend
'
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
